// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_llm_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_llm_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_llm_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_llm_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_llm_2eproto;
namespace llm {
class ConverseRequest;
struct ConverseRequestDefaultTypeInternal;
extern ConverseRequestDefaultTypeInternal _ConverseRequest_default_instance_;
class ConverseResponse;
struct ConverseResponseDefaultTypeInternal;
extern ConverseResponseDefaultTypeInternal _ConverseResponse_default_instance_;
}  // namespace llm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace llm {

// ===================================================================


// -------------------------------------------------------------------

class ConverseResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:llm.ConverseResponse) */ {
 public:
  inline ConverseResponse() : ConverseResponse(nullptr) {}
  ~ConverseResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ConverseResponse(::google::protobuf::internal::ConstantInitialized);

  inline ConverseResponse(const ConverseResponse& from)
      : ConverseResponse(nullptr, from) {}
  ConverseResponse(ConverseResponse&& from) noexcept
    : ConverseResponse() {
    *this = ::std::move(from);
  }

  inline ConverseResponse& operator=(const ConverseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConverseResponse& operator=(ConverseResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConverseResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConverseResponse* internal_default_instance() {
    return reinterpret_cast<const ConverseResponse*>(
               &_ConverseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ConverseResponse& a, ConverseResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ConverseResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConverseResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConverseResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConverseResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConverseResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ConverseResponse& from) {
    ConverseResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ConverseResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "llm.ConverseResponse";
  }
  protected:
  explicit ConverseResponse(::google::protobuf::Arena* arena);
  ConverseResponse(::google::protobuf::Arena* arena, const ConverseResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
    kEndOfResponseFieldNumber = 2,
  };
  // repeated string text = 1;
  int text_size() const;
  private:
  int _internal_text_size() const;

  public:
  void clear_text() ;
  const std::string& text(int index) const;
  std::string* mutable_text(int index);
  void set_text(int index, const std::string& value);
  void set_text(int index, std::string&& value);
  void set_text(int index, const char* value);
  void set_text(int index, const char* value, std::size_t size);
  void set_text(int index, absl::string_view value);
  std::string* add_text();
  void add_text(const std::string& value);
  void add_text(std::string&& value);
  void add_text(const char* value);
  void add_text(const char* value, std::size_t size);
  void add_text(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& text() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_text();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_text() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_text();

  public:
  // bool end_of_response = 2;
  void clear_end_of_response() ;
  bool end_of_response() const;
  void set_end_of_response(bool value);

  private:
  bool _internal_end_of_response() const;
  void _internal_set_end_of_response(bool value);

  public:
  // @@protoc_insertion_point(class_scope:llm.ConverseResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      33, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField<std::string> text_;
    bool end_of_response_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_llm_2eproto;
};// -------------------------------------------------------------------

class ConverseRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:llm.ConverseRequest) */ {
 public:
  inline ConverseRequest() : ConverseRequest(nullptr) {}
  ~ConverseRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ConverseRequest(::google::protobuf::internal::ConstantInitialized);

  inline ConverseRequest(const ConverseRequest& from)
      : ConverseRequest(nullptr, from) {}
  ConverseRequest(ConverseRequest&& from) noexcept
    : ConverseRequest() {
    *this = ::std::move(from);
  }

  inline ConverseRequest& operator=(const ConverseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConverseRequest& operator=(ConverseRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConverseRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConverseRequest* internal_default_instance() {
    return reinterpret_cast<const ConverseRequest*>(
               &_ConverseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConverseRequest& a, ConverseRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ConverseRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConverseRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConverseRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConverseRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConverseRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ConverseRequest& from) {
    ConverseRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ConverseRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "llm.ConverseRequest";
  }
  protected:
  explicit ConverseRequest(::google::protobuf::Arena* arena);
  ConverseRequest(::google::protobuf::Arena* arena, const ConverseRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* value);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:llm.ConverseRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      32, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr text_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_llm_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConverseRequest

// string text = 1;
inline void ConverseRequest::clear_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.text_.ClearToEmpty();
}
inline const std::string& ConverseRequest::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:llm.ConverseRequest.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ConverseRequest::set_text(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:llm.ConverseRequest.text)
}
inline std::string* ConverseRequest::mutable_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:llm.ConverseRequest.text)
  return _s;
}
inline const std::string& ConverseRequest::_internal_text() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.text_.Get();
}
inline void ConverseRequest::_internal_set_text(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.text_.Set(value, GetArena());
}
inline std::string* ConverseRequest::_internal_mutable_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.text_.Mutable( GetArena());
}
inline std::string* ConverseRequest::release_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:llm.ConverseRequest.text)
  return _impl_.text_.Release();
}
inline void ConverseRequest::set_allocated_text(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.text_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_.IsDefault()) {
          _impl_.text_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:llm.ConverseRequest.text)
}

// -------------------------------------------------------------------

// ConverseResponse

// repeated string text = 1;
inline int ConverseResponse::_internal_text_size() const {
  return _internal_text().size();
}
inline int ConverseResponse::text_size() const {
  return _internal_text_size();
}
inline void ConverseResponse::clear_text() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.text_.Clear();
}
inline std::string* ConverseResponse::add_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_text()->Add();
  // @@protoc_insertion_point(field_add_mutable:llm.ConverseResponse.text)
  return _s;
}
inline const std::string& ConverseResponse::text(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:llm.ConverseResponse.text)
  return _internal_text().Get(index);
}
inline std::string* ConverseResponse::mutable_text(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:llm.ConverseResponse.text)
  return _internal_mutable_text()->Mutable(index);
}
inline void ConverseResponse::set_text(int index, const std::string& value) {
  _internal_mutable_text()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:llm.ConverseResponse.text)
}
inline void ConverseResponse::set_text(int index, std::string&& value) {
  _internal_mutable_text()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:llm.ConverseResponse.text)
}
inline void ConverseResponse::set_text(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_text()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:llm.ConverseResponse.text)
}
inline void ConverseResponse::set_text(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_text()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:llm.ConverseResponse.text)
}
inline void ConverseResponse::set_text(int index, absl::string_view value) {
  _internal_mutable_text()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:llm.ConverseResponse.text)
}
inline void ConverseResponse::add_text(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_text()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:llm.ConverseResponse.text)
}
inline void ConverseResponse::add_text(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_text()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:llm.ConverseResponse.text)
}
inline void ConverseResponse::add_text(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_text()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:llm.ConverseResponse.text)
}
inline void ConverseResponse::add_text(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_text()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:llm.ConverseResponse.text)
}
inline void ConverseResponse::add_text(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_text()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:llm.ConverseResponse.text)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ConverseResponse::text() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:llm.ConverseResponse.text)
  return _internal_text();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ConverseResponse::mutable_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:llm.ConverseResponse.text)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_text();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ConverseResponse::_internal_text() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.text_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ConverseResponse::_internal_mutable_text() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.text_;
}

// bool end_of_response = 2;
inline void ConverseResponse::clear_end_of_response() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.end_of_response_ = false;
}
inline bool ConverseResponse::end_of_response() const {
  // @@protoc_insertion_point(field_get:llm.ConverseResponse.end_of_response)
  return _internal_end_of_response();
}
inline void ConverseResponse::set_end_of_response(bool value) {
  _internal_set_end_of_response(value);
  // @@protoc_insertion_point(field_set:llm.ConverseResponse.end_of_response)
}
inline bool ConverseResponse::_internal_end_of_response() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.end_of_response_;
}
inline void ConverseResponse::_internal_set_end_of_response(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.end_of_response_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace llm


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_llm_2eproto_2epb_2eh
