// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: llm.proto

#include "llm.pb.h"
#include "llm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace llm {

static const char* LLM_method_names[] = {
  "/llm.LLM/Converse",
};

std::unique_ptr< LLM::Stub> LLM::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LLM::Stub> stub(new LLM::Stub(channel, options));
  return stub;
}

LLM::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Converse_(LLM_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* LLM::Stub::ConverseRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::llm::ConverseRequest, ::llm::ConverseResponse>::Create(channel_.get(), rpcmethod_Converse_, context);
}

void LLM::Stub::async::Converse(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::llm::ConverseRequest,::llm::ConverseResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::llm::ConverseRequest,::llm::ConverseResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Converse_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* LLM::Stub::AsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::llm::ConverseRequest, ::llm::ConverseResponse>::Create(channel_.get(), cq, rpcmethod_Converse_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* LLM::Stub::PrepareAsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::llm::ConverseRequest, ::llm::ConverseResponse>::Create(channel_.get(), cq, rpcmethod_Converse_, context, false, nullptr);
}

LLM::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LLM_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< LLM::Service, ::llm::ConverseRequest, ::llm::ConverseResponse>(
          [](LLM::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::llm::ConverseResponse,
             ::llm::ConverseRequest>* stream) {
               return service->Converse(ctx, stream);
             }, this)));
}

LLM::Service::~Service() {
}

::grpc::Status LLM::Service::Converse(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace llm

