// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm.proto

#include "llm.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace llm {

inline constexpr ConverseResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : text_{},
        end_of_response_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConverseResponse::ConverseResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConverseResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConverseResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConverseResponseDefaultTypeInternal() {}
  union {
    ConverseResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConverseResponseDefaultTypeInternal _ConverseResponse_default_instance_;

inline constexpr ConverseRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConverseRequest::ConverseRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConverseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConverseRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConverseRequestDefaultTypeInternal() {}
  union {
    ConverseRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConverseRequestDefaultTypeInternal _ConverseRequest_default_instance_;
}  // namespace llm
static ::_pb::Metadata file_level_metadata_llm_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_llm_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_llm_2eproto = nullptr;
const ::uint32_t TableStruct_llm_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::llm::ConverseRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::llm::ConverseRequest, _impl_.text_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::llm::ConverseResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::llm::ConverseResponse, _impl_.text_),
    PROTOBUF_FIELD_OFFSET(::llm::ConverseResponse, _impl_.end_of_response_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::llm::ConverseRequest)},
        {9, -1, -1, sizeof(::llm::ConverseResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::llm::_ConverseRequest_default_instance_._instance,
    &::llm::_ConverseResponse_default_instance_._instance,
};
const char descriptor_table_protodef_llm_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\tllm.proto\022\003llm\"\037\n\017ConverseRequest\022\014\n\004t"
    "ext\030\001 \001(\t\"9\n\020ConverseResponse\022\014\n\004text\030\001 "
    "\003(\t\022\027\n\017end_of_response\030\002 \001(\0102D\n\003LLM\022=\n\010C"
    "onverse\022\024.llm.ConverseRequest\032\025.llm.Conv"
    "erseResponse\"\000(\0010\001B/Z-github.com/google/"
    "gemma.cpp/contrib/server/pbb\006proto3"
};
static ::absl::once_flag descriptor_table_llm_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_llm_2eproto = {
    false,
    false,
    235,
    descriptor_table_protodef_llm_2eproto,
    "llm.proto",
    &descriptor_table_llm_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_llm_2eproto::offsets,
    file_level_metadata_llm_2eproto,
    file_level_enum_descriptors_llm_2eproto,
    file_level_service_descriptors_llm_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_llm_2eproto_getter() {
  return &descriptor_table_llm_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_llm_2eproto(&descriptor_table_llm_2eproto);
namespace llm {
// ===================================================================

class ConverseRequest::_Internal {
 public:
};

ConverseRequest::ConverseRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:llm.ConverseRequest)
}
inline PROTOBUF_NDEBUG_INLINE ConverseRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : text_(arena, from.text_),
        _cached_size_{0} {}

ConverseRequest::ConverseRequest(
    ::google::protobuf::Arena* arena,
    const ConverseRequest& from)
    : ::google::protobuf::Message(arena) {
  ConverseRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:llm.ConverseRequest)
}
inline PROTOBUF_NDEBUG_INLINE ConverseRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : text_(arena),
        _cached_size_{0} {}

inline void ConverseRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ConverseRequest::~ConverseRequest() {
  // @@protoc_insertion_point(destructor:llm.ConverseRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConverseRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.text_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ConverseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:llm.ConverseRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConverseRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2> ConverseRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConverseRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string text = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ConverseRequest, _impl_.text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string text = 1;
    {PROTOBUF_FIELD_OFFSET(ConverseRequest, _impl_.text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\4\0\0\0\0\0\0"
    "llm.ConverseRequest"
    "text"
  }},
};

::uint8_t* ConverseRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:llm.ConverseRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    const std::string& _s = this->_internal_text();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llm.ConverseRequest.text");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llm.ConverseRequest)
  return target;
}

::size_t ConverseRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llm.ConverseRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_text());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ConverseRequest::_class_data_ = {
    ConverseRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ConverseRequest::GetClassData() const {
  return &_class_data_;
}

void ConverseRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ConverseRequest*>(&to_msg);
  auto& from = static_cast<const ConverseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:llm.ConverseRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConverseRequest::CopyFrom(const ConverseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llm.ConverseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConverseRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ConverseRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ConverseRequest::InternalSwap(ConverseRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
}

::google::protobuf::Metadata ConverseRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_llm_2eproto_getter, &descriptor_table_llm_2eproto_once,
      file_level_metadata_llm_2eproto[0]);
}
// ===================================================================

class ConverseResponse::_Internal {
 public:
};

ConverseResponse::ConverseResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:llm.ConverseResponse)
}
inline PROTOBUF_NDEBUG_INLINE ConverseResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : text_{visibility, arena, from.text_},
        _cached_size_{0} {}

ConverseResponse::ConverseResponse(
    ::google::protobuf::Arena* arena,
    const ConverseResponse& from)
    : ::google::protobuf::Message(arena) {
  ConverseResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.end_of_response_ = from._impl_.end_of_response_;

  // @@protoc_insertion_point(copy_constructor:llm.ConverseResponse)
}
inline PROTOBUF_NDEBUG_INLINE ConverseResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : text_{visibility, arena},
        _cached_size_{0} {}

inline void ConverseResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.end_of_response_ = {};
}
ConverseResponse::~ConverseResponse() {
  // @@protoc_insertion_point(destructor:llm.ConverseResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConverseResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ConverseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:llm.ConverseResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.Clear();
  _impl_.end_of_response_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConverseResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 33, 2> ConverseResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConverseResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool end_of_response = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ConverseResponse, _impl_.end_of_response_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ConverseResponse, _impl_.end_of_response_)}},
    // repeated string text = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ConverseResponse, _impl_.text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string text = 1;
    {PROTOBUF_FIELD_OFFSET(ConverseResponse, _impl_.text_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // bool end_of_response = 2;
    {PROTOBUF_FIELD_OFFSET(ConverseResponse, _impl_.end_of_response_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\24\4\0\0\0\0\0\0"
    "llm.ConverseResponse"
    "text"
  }},
};

::uint8_t* ConverseResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:llm.ConverseResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string text = 1;
  for (int i = 0, n = this->_internal_text_size(); i < n; ++i) {
    const auto& s = this->_internal_text().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "llm.ConverseResponse.text");
    target = stream->WriteString(1, s, target);
  }

  // bool end_of_response = 2;
  if (this->_internal_end_of_response() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_end_of_response(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llm.ConverseResponse)
  return target;
}

::size_t ConverseResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llm.ConverseResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string text = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_text().size());
  for (int i = 0, n = _internal_text().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_text().Get(i));
  }
  // bool end_of_response = 2;
  if (this->_internal_end_of_response() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ConverseResponse::_class_data_ = {
    ConverseResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ConverseResponse::GetClassData() const {
  return &_class_data_;
}

void ConverseResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ConverseResponse*>(&to_msg);
  auto& from = static_cast<const ConverseResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:llm.ConverseResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_text()->MergeFrom(from._internal_text());
  if (from._internal_end_of_response() != 0) {
    _this->_internal_set_end_of_response(from._internal_end_of_response());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConverseResponse::CopyFrom(const ConverseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llm.ConverseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConverseResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ConverseResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ConverseResponse::InternalSwap(ConverseResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.text_.InternalSwap(&other->_impl_.text_);
        swap(_impl_.end_of_response_, other->_impl_.end_of_response_);
}

::google::protobuf::Metadata ConverseResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_llm_2eproto_getter, &descriptor_table_llm_2eproto_once,
      file_level_metadata_llm_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace llm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
