// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: llm.proto
#ifndef GRPC_llm_2eproto__INCLUDED
#define GRPC_llm_2eproto__INCLUDED

#include "llm.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace llm {

// LLM serves the large language model.
class LLM final {
 public:
  static constexpr char const* service_full_name() {
    return "llm.LLM";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Runs a conversational session with the LLM.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>> Converse(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>>(ConverseRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>> AsyncConverse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>>(AsyncConverseRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>> PrepareAsyncConverse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>>(PrepareAsyncConverseRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Runs a conversational session with the LLM.
      virtual void Converse(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::llm::ConverseRequest,::llm::ConverseResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>* ConverseRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>* AsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::llm::ConverseRequest, ::llm::ConverseResponse>* PrepareAsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>> Converse(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>>(ConverseRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>> AsyncConverse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>>(AsyncConverseRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>> PrepareAsyncConverse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>>(PrepareAsyncConverseRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Converse(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::llm::ConverseRequest,::llm::ConverseResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* ConverseRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* AsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::llm::ConverseRequest, ::llm::ConverseResponse>* PrepareAsyncConverseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Converse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Runs a conversational session with the LLM.
    virtual ::grpc::Status Converse(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Converse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Converse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Converse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Converse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConverse(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Converse<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Converse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Converse() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::llm::ConverseRequest, ::llm::ConverseResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Converse(context); }));
    }
    ~WithCallbackMethod_Converse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Converse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::llm::ConverseRequest, ::llm::ConverseResponse>* Converse(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Converse<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Converse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Converse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Converse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Converse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Converse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Converse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Converse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Converse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConverse(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Converse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Converse() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Converse(context); }));
    }
    ~WithRawCallbackMethod_Converse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Converse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::llm::ConverseResponse, ::llm::ConverseRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Converse(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace llm


#endif  // GRPC_llm_2eproto__INCLUDED
