#!/usr/bin/env python3
r"""Generates dsv4_unicode_ranges.inc from Python's unicodedata.

The DeepSeek V4 tokenizer.json pre-tokenizer Split patterns use the regex
classes \p{L}, \p{M}, \p{N}, \p{P}, \p{S}; dsv4_tokenizer.cc matches them
against these tables. Run with a Python whose unicodedata has the desired
Unicode version (3.12 = 15.0.0):

  python3 gen_unicode_ranges.py > dsv4_unicode_ranges.inc
"""

import sys
import unicodedata

# (table name, Unicode general-category major class)
TABLES = [
    ("kLetterRanges", "L"),
    ("kMarkRanges", "M"),
    ("kNumberRanges", "N"),
    ("kPunctRanges", "P"),
    ("kSymbolRanges", "S"),
]

PER_LINE = 6


def main():
  ranges = {major: [] for _, major in TABLES}
  for cp in range(0x110000):
    r = ranges.get(unicodedata.category(chr(cp))[0])
    if r is None:
      continue
    if r and r[-1][1] == cp - 1:
      r[-1][1] = cp
    else:
      r.append([cp, cp])

  out = sys.stdout
  out.write(
      "// Generated by gen_unicode_ranges.py from Python unicodedata "
      f"(Unicode {unicodedata.unidata_version}).\n"
  )
  out.write(
      "// Inclusive [lo, hi] codepoint ranges, sorted ascending. "
      "Do not edit by hand.\n\n"
  )
  for name, major in TABLES:
    out.write(f"static constexpr URange {name}[] = {{\n")
    rows = ranges[major]
    for i in range(0, len(rows), PER_LINE):
      cells = " ".join(
          f"{{0x{lo:X}, 0x{hi:X}}}," for lo, hi in rows[i : i + PER_LINE]
      )
      out.write(f"    {cells}\n")
    out.write("};\n\n")


if __name__ == "__main__":
  main()
